### ISSUE TITLE
Very high number of characters marked as DELETED

### ISSUE THREAD

**Issue by Pricetx** [XIVStats/XIVStats-Gatherer-Java#63] opened 2022-01-01 12:00 UTC
We have just completed a new census run for December 2021. The stats show a remarkably low number of characters. On further inspection, the number of DELETED characters seems extremely high:

SELECT COUNT(*) FROM tblplayers;
34,329,901

SELECT COUNT(*) FROM tblplayers where character_status = "DELETED";
28,142,672

The result is that the census reckons there are only 6,187,229 characters in existance.

We should probably investigate and try to find some examples of characters the database reckons are deleted but actually aren't to enable us to troubleshoot further.

**Comment by ReidWeb** [comment] 2022-01-01 12:08
Can you send me over some creds for database I'll take a look

**Comment by Pricetx** [comment] 2022-01-01 15:37
Credentials have been provided.

**Comment by ReidWeb** [comment] 2022-01-01 21:11
# Results of initial investigation

The first character I went to check in the database does not exist [Aurora Nyx, 38531003](https://eu.finalfantasyxiv.com/lodestone/character/38531003). As you can see this is a character has a significant number of mounts.

![image](https://user-images.githubusercontent.com/3649078/147860063-0b3b325c-9ff9-4c07-b65a-03e3d4f1048b.png)

In the above screenshot I've included my own character ID for reference to confirm that I have the correct syntax.

The characters on either side of her do not appear to exist either, running the query below yields **NO** results

```sql
USE ffxivcensus;
USE ffxivcensus;
SELECT * FROM tblplayers
WHERE  id > 38531000 and id <38531100;
```

Yet the below does (confirming syntax)

```sql
USE ffxivcensus;
SELECT * FROM tblplayers
WHERE  id > 11886900 and id <11887000;
```

# Summary

There appear to be 'blocks' where there are not being players parsed.

# Theory

@matthewhillier With the rate limiting, do we account for the additional GET requests performed to retrieve the mount page, minion mage, and each mount/minion thumbnail presented on those pages?

If that's the case, what occurs in the instance we hit a 5xx error on a thumbnail or mount/minion page request? I'm wondering if we're "losing" those characters because we hit a 5xx on a 'sub page'

I'm spinning up a small run around the range of Aurora in the dev instance right now.

**Comment by ReidWeb** [comment] 2022-01-01 21:34
Update: Found why Aurora doesn't exist

```sql
USE ffxivcensus;
SELECT MAX(id)
FROM tblplayers;
```

Yields  back `34352190`. It appears to be giving up well short of her

**Comment by ReidWeb** [comment] 2022-01-01 21:43
Please disregard above notes around Aurora, Jonathan found the cause there was a fatal error for that char.

I'll dive further into characters in the range we've already parsed tomorrow and verify they're meant to be marked as deleted

**Comment by matthewhillier** [comment] 2022-01-03 03:50
Hmm.. the only thing that should trigger a DELETED state is if the server returns a HTTP 404 response. All other errors, including those typically generated by the Lodestone in response to overload or rate-limiting, should eventually just result in a skip and note in the logs. I had some errors with Mounts/Minions while doing the 6.0 updates, and they only produced 5xx errors - so assuming that's consistent, I don't think it's that.

I wonder whether the lodestone was down for maintenance when we ran the gatherer? Which is the only other scenario that I can think of that could result in 404 responses instead of something else? Did we bump into the 6.01 downtime? If that does turn out to be the case, might need to think of some additional defensive coding to take into consideration maintenance windows etc.

Perhaps it's worth re-running again against a copy of the Nov 2021 DB (or just running against a fresh DB) and seeing if we get a similar result? (Perhaps do it after the 6.05 update has dropped?).

**Comment by ReidWeb** [comment] 2022-01-03 08:43
We would have run across the 6.01 down time yeah.

**Comment by Pricetx** [comment] 2022-01-05 22:18
I've just kicked off a census to capture the IDs after 34,353,190 (unrelated issue).

Here's a short extract of the active census:
`
[2022-01-05 22:10:35,087] [pool-1-thread-9] INFO com.ffxivcensus.gatherer.task.GathererTask.result  - 34355374 - DELETED
[2022-01-05 22:10:35,087] [pool-1-thread-9] DEBUG com.ffxivcensus.gatherer.task.GathererTask  - Starting evaluation of player ID: 34355438
[2022-01-05 22:10:35,114] [pool-1-thread-45] INFO com.ffxivcensus.gatherer.lodestone.ProductionLodestonePageLoader  - Character 34355379 does not exist. (404)
[2022-01-05 22:10:35,123] [pool-1-thread-45] INFO com.ffxivcensus.gatherer.task.GathererTask.result  - 34355379 - DELETED
[2022-01-05 22:10:35,123] [pool-1-thread-45] DEBUG com.ffxivcensus.gatherer.task.GathererTask  - Starting evaluation of player ID: 34355439
[2022-01-05 22:10:35,163] [pool-1-thread-17] INFO com.ffxivcensus.gatherer.lodestone.ProductionLodestonePageLoader  - Character 34355377 does not exist. (404)
[2022-01-05 22:10:35,173] [pool-1-thread-17] INFO com.ffxivcensus.gatherer.task.GathererTask.result  - 34355377 - DELETED
[2022-01-05 22:10:35,173] [pool-1-thread-17] DEBUG com.ffxivcensus.gatherer.task.GathererTask  - Starting evaluation of player ID: 34355440
[2022-01-05 22:10:35,179] [pool-1-thread-18] INFO com.ffxivcensus.gatherer.lodestone.ProductionLodestonePageLoader  - Character 34355378 does not exist. (404)
[2022-01-05 22:10:35,190] [pool-1-thread-18] INFO com.ffxivcensus.gatherer.task.GathererTask.result  - 34355378 - DELETED
[2022-01-05 22:10:35,190] [pool-1-thread-18] DEBUG com.ffxivcensus.gatherer.task.GathererTask  - Starting evaluation of player ID: 34355441
[2022-01-05 22:10:35,342] [pool-1-thread-43] INFO com.ffxivcensus.gatherer.lodestone.ProductionLodestonePageLoader  - Character 34355381 does not exist. (404)
[2022-01-05 22:10:35,354] [pool-1-thread-43] INFO com.ffxivcensus.gatherer.task.GathererTask.result  - 34355381 - DELETED
`

It mentions that it reckons the following IDs are all deleted:
- 34355374
- 34355379
- 34355377
- 34355378
- 34355381

I have checked these IDs in the lodestone. All 5 of them exist in the lodestone, and we can rule out a lodestone outage because this particular census is running as I type this.

I don't have any theories on why this is happening at this time, but I can at least confirm that it is marking some people as ACTIVE/INACTIVE so it's not doing this to 100% of IDs.

**Comment by ReidWeb** [comment] 2022-01-09 17:29
Doing some investigation, in addition to the 404's presented in the console of characters that exist, database is yielding a DELETED Status against recorded characters who exist

Executed query
```sql
SELECT id, name, character_status FROM tblplayers
WHERE id = 1;
```

Results

|id|name|character_status|
|--|--|--|
|1|Macaroni Gratin|DELETED|


[This character most definitely exists](https://eu.finalfantasyxiv.com/lodestone/character/1)

**Comment by ReidWeb** [comment] 2022-01-09 17:32
@Pricetx at this time I would propose we cease publishing of further census information until such a time as that the cause can be identified.

**Comment by ReidWeb** [comment] 2022-01-09 17:53
I have selected a random sample of those characters marked as `DELETED`  from the December run, and produced the attached csv for input into my test program.

```sql
SELECT id FROM tblplayers
WHERE id < 1000000 and character_status = 'DELETED' and rand() <= .3
LIMIT 1000;
```


[ffxivcensus_tblplayers.csv](https://github.com/XIVStats/XIVStats-Gatherer-Java/files/7835588/ffxivcensus_tblplayers.csv)
 
Of these 1000 ids, 100 were found to exist, 892 not to exist and 8 had issues I had not accounted for in my test script.

![image](https://user-images.githubusercontent.com/3649078/148694111-16002f62-71be-45ff-9f15-4c67b42fd3f6.png)

Those ids found to exist in my sample can be found below

```json
[
  9,
  20,
  32,
  50,
  234,
  258,
  265,
  301,
  330,
  334,
  349,
  360,
  406,
  407,
  416,
  418,
  429,
  478,
  479,
  536,
  538,
  542,
  558,
  578,
  624,
  637,
  644,
  745,
  801,
  851,
  853,
  887,
  922,
  981,
  1052,
  1065,
  1072,
  1152,
  1187,
  1214,
  1250,
  1311,
  1318,
  1365,
  1455,
  1483,
  1520,
  1549,
  1557,
  1570,
  1578,
  1637,
  1695,
  1724,
  1807,
  1823,
  1831,
  1908,
  1931,
  1967,
  2012,
  2135,
  2341,
  2363,
  2389,
  2427,
  2574,
  2579,
  2668,
  2693,
  2749,
  2790,
  2943,
  2951,
  2957,
  2989,
  2990,
  3005,
  3056,
  3196,
  3262,
  3304,
  3326,
  3459,
  3502,
  3580,
  3625,
  3702,
  3711,
  3736,
  3765,
  3790,
  3821,
  3870,
  3877,
  3914,
  3968,
  3997,
  4022,
  4176
]
```

I'm going to re-run this with a higher range, to ascertain whether the mis-identification rate of 10% applies at other ranges.

**Comment by ReidWeb** [comment] 2022-01-09 18:07
Query at higher range

```sql
SELECT id FROM tblplayers
WHERE id > 33000000 AND id < 34000000 and character_status = 'DELETED' and rand() <= .3
LIMIT 1000;
```
[ffxivcensus_tblplayers_sample_2.csv](https://github.com/XIVStats/XIVStats-Gatherer-Java/files/7835596/ffxivcensus_tblplayers_sample_2.csv)

Running these through my program, 494 of these were found to exist, 502 were found to not exist as expected. I hit timeouts on the other 4

![image](https://user-images.githubusercontent.com/3649078/148694626-b5e6cf42-b70a-4564-9d75-172a65b12f7f.png)


Characters found that the java runner labelled as DELETED
```json
[
  33000006,
  33000046,
  33000049,
  33000064,
  33000068,
  33000074,
  33000081,
  33000084,
  33000090,
  33000096,
  33000109,
  33000114,
  33000128,
  33000158,
  33000162,
  33000165,
  33000183,
  33000186,
  33000191,
  33000194,
  33000209,
  33000211,
  33000217,
  33000227,
  33000230,
  33000232,
  33000241,
  33000243,
  33000250,
  33000256,
  33000270,
  33000273,
  33000287,
  33000292,
  33000295,
  33000297,
  33000304,
  33000328,
  33000332,
  33000342,
  33000369,
  33000374,
  33000376,
  33000384,
  33000425,
  33000426,
  33000442,
  33000447,
  33000448,
  33000452,
  33000470,
  33000488,
  33000497,
  33000500,
  33000518,
  33000522,
  33000528,
  33000529,
  33000530,
  33000538,
  33000545,
  33000551,
  33000568,
  33000569,
  33000580,
  33000589,
  33000603,
  33000608,
  33000637,
  33000652,
  33000658,
  33000660,
  33000675,
  33000686,
  33000698,
  33000700,
  33000710,
  33000715,
  33000717,
  33000725,
  33000732,
  33000738,
  33000741,
  33000742,
  33000769,
  33000771,
  33000780,
  33000783,
  33000788,
  33000817,
  33000819,
  33000823,
  33000827,
  33000831,
  33000834,
  33000839,
  33000847,
  33000852,
  33000859,
  33000865,
  33000877,
  33000896,
  33000913,
  33000926,
  33000927,
  33000928,
  33000935,
  33000936,
  33000948,
  33000953,
  33000963,
  33000969,
  33000998,
  33000999,
  33001000,
  33001002,
  33001019,
  33001043,
  33001054,
  33001057,
  33001061,
  33001084,
  33001086,
  33001096,
  33001102,
  33001117,
  33001127,
  33001128,
  33001137,
  33001155,
  33001158,
  33001159,
  33001163,
  33001168,
  33001170,
  33001171,
  33001175,
  33001177,
  33001184,
  33001187,
  33001194,
  33001210,
  33001213,
  33001216,
  33001222,
  33001250,
  33001268,
  33001286,
  33001287,
  33001301,
  33001308,
  33001310,
  33001315,
  33001317,
  33001324,
  33001325,
  33001339,
  33001345,
  33001347,
  33001355,
  33001372,
  33001382,
  33001389,
  33001396,
  33001419,
  33001456,
  33001464,
  33001468,
  33001474,
  33001483,
  33001490,
  33001516,
  33001521,
  33001522,
  33001539,
  33001548,
  33001561,
  33001567,
  33001585,
  33001601,
  33001602,
  33001604,
  33001619,
  33001631,
  33001632,
  33001652,
  33001656,
  33001659,
  33001663,
  33001668,
  33001683,
  33001691,
  33001702,
  33001710,
  33001714,
  33001715,
  33001724,
  33001725,
  33001733,
  33001743,
  33001749,
  33001754,
  33001773,
  33001776,
  33001786,
  33001793,
  33001808,
  33001820,
  33001827,
  33001834,
  33001848,
  33001849,
  33001862,
  33001863,
  33001865,
  33001884,
  33001892,
  33001898,
  33001899,
  33001900,
  33001920,
  33001940,
  33001941,
  33001942,
  33001943,
  33001944,
  33001946,
  33001949,
  33001953,
  33001958,
  33001968,
  33001973,
  33001974,
  33001982,
  33001988,
  33001990,
  33002004,
  33002009,
  33002012,
  33002052,
  33002067,
  33002070,
  33002072,
  33002078,
  33002090,
  33002092,
  33002096,
  33002098,
  33002100,
  33002101,
  33002114,
  33002119,
  33002129,
  33002142,
  33002145,
  33002160,
  33002175,
  33002186,
  33002197,
  33002209,
  33002211,
  33002218,
  33002222,
  33002245,
  33002251,
  33002253,
  33002264,
  33002277,
  33002278,
  33002286,
  33002287,
  33002293,
  33002294,
  33002297,
  33002312,
  33002323,
  33002324,
  33002339,
  33002344,
  33002354,
  33002355,
  33002359,
  33002366,
  33002379,
  33002382,
  33002384,
  33002399,
  33002419,
  33002420,
  33002422,
  33002431,
  33002433,
  33002434,
  33002443,
  33002461,
  33002478,
  33002501,
  33002512,
  33002523,
  33002530,
  33002540,
  33002546,
  33002553,
  33002565,
  33002578,
  33002579,
  33002584,
  33002587,
  33002594,
  33002605,
  33002608,
  33002613,
  33002620,
  33002621,
  33002632,
  33002645,
  33002651,
  33002662,
  33002665,
  33002670,
  33002674,
  33002686,
  33002695,
  33002700,
  33002709,
  33002710,
  33002712,
  33002721,
  33002733,
  33002739,
  33002750,
  33002751,
  33002765,
  33002776,
  33002784,
  33002790,
  33002795,
  33002799,
  33002819,
  33002825,
  33002827,
  33002832,
  33002843,
  33002844,
  33002847,
  33002848,
  33002857,
  33002871,
  33002874,
  33002876,
  33002877,
  33002878,
  33002880,
  33002890,
  33002894,
  33002912,
  33002913,
  33002917,
  33002928,
  33002929,
  33002931,
  33002932,
  33002956,
  33002964,
  33002974,
  33002982,
  33002984,
  33002990,
  33003011,
  33003040,
  33003047,
  33003072,
  33003082,
  33003105,
  33003106,
  33003121,
  33003153,
  33003154,
  33003160,
  33003167,
  33003171,
  33003174,
  33003188,
  33003192,
  33003200,
  33003204,
  33003205,
  33003231,
  33003268,
  33003276,
  33003278,
  33003291,
  33003296,
  33003297,
  33003301,
  33003303,
  33003316,
  33003321,
  33003327,
  33003334,
  33003350,
  33003354,
  33003358,
  33003361,
  33003365,
  33003366,
  33003372,
  33003375,
  33003387,
  33003397,
  33003398,
  33003400,
  33003409,
  33003446,
  33003448,
  33003450,
  33003452,
  33003460,
  33003470,
  33003479,
  33003482,
  33003492,
  33003495,
  33003514,
  33003517,
  33003520,
  33003523,
  33003530,
  33003535,
  33003579,
  33003581,
  33003590,
  33003598,
  33003607,
  33003612,
  33003613,
  33003618,
  33003629,
  33003631,
  33003644,
  33003646,
  33003647,
  33003653,
  33003654,
  33003662,
  33003668,
  33003675,
  33003699,
  33003703,
  33003705,
  33003720,
  33003724,
  33003743,
  33003782,
  33003784,
  33003794,
  33003819,
  33003820,
  33003834,
  33003842,
  33003846,
  33003850,
  33003869,
  33003890,
  33003896,
  33003912,
  33003914,
  33003931,
  33003937,
  33003943,
  33003951,
  33003956,
  33003960,
  33003973,
  33003974,
  33003977,
  33003994,
  33004003,
  33004035,
  33004041,
  33004043,
  33004048,
  33004073,
  33004077,
  33004083,
  33004090,
  33004093,
  33004095,
  33004100,
  33004105,
  33004139,
  33004152,
  33004186,
  33004251
]
```

This is a 49.4% rate of the characters being mis-labelled.

**Comment by ReidWeb** [comment] 2022-01-09 18:37
@Pricetx was able to confirm that the highest recorded ID in the database used to seed the characters to parse for this latest census was 27,300,328.

Given the range used for my sample above was in the `33,000,000` --> `34,000,000` range, we can know that these characters in this sample were parsed by the latest version of the code.

As such I can confirm that this appears to be an issue with the codebase as it stands in certain scenarios. 

Corrective action required as below:
1. Bug identified, fixed, deployed
2. Create a new database from scratch, and use that with the fixed code.

## Next steps as regards identification of bug

Now we have confirmed the presence of a bug, we need to work on identification of the root cause. My abilities in this regard are somewhat limited, and appreciate this is a hard one to get into. It seems to be environmental.

To help confirm environmental nature of it can we run a run into the dev instance starting with `33000000` and ending with `33005000`. (@Pricetx as i currently have no ability to do so in the host), with a thread count of `1`.

**Comment by ReidWeb** [comment] 2022-01-09 19:04
Even with 1 thread, and a db not seeded with characters at that range it's recording them as deleted

```
[2022-01-09 19:00:16,011] [pool-1-thread-1] DEBUG com.ffxivcensus.gatherer.task.GathererTask  - Starting evaluation of player ID: 33000006
[2022-01-09 19:00:18,205] [pool-2-thread-1] DEBUG com.ffxivcensus.gatherer.task.LevemeteTask  - Loading new jobs into the gatherer
[2022-01-09 19:00:21,670] [pool-1-thread-1] INFO com.ffxivcensus.gatherer.lodestone.ProductionLodestonePageLoader  - Character 33000006 does not exist. (404)
[2022-01-09 19:00:21,687] [pool-1-thread-1] INFO com.ffxivcensus.gatherer.task.GathererTask.result  - 33000006 - DELETED
```

[33000006](https://eu.finalfantasyxiv.com/lodestone/character/33000006) exists

**Comment by ReidWeb** [comment] 2022-01-09 19:11
Good news, through running the unit tests locally against 33000006, I am able to reproduce them having a status of `DELETED`

![image](https://user-images.githubusercontent.com/3649078/148697024-f6b9e754-0e66-4a44-8fce-107d7f61963b.png)

Working to ascertain the root cause now

**Comment by ReidWeb** [comment] 2022-01-09 19:36
I believe I have ascertained the root cause.

Player's [33000008](https://eu.finalfantasyxiv.com/lodestone/character/33000008) and [33000006](https://eu.finalfantasyxiv.com/lodestone/character/33000006) both do not allow the mount and minion pages to be viewed.

And per @crakila'ss poking about of my ids provided above, [33000046](https://eu.finalfantasyxiv.com/lodestone/character/33000046) has no minions.

From investigating the stack trace, a `CharacterDeletedException` is created on [PlayerBuilder.java#L200](https://github.com/XIVStats/XIVStats-Gatherer-Java/blob/d594080f12fe5c75f2801e352a2f02c371c78881/src/main/java/com/ffxivcensus/gatherer/player/PlayerBuilder.java#L200) if no mounts are present, and from [PlayerBuilder.java#L204](https://github.com/XIVStats/XIVStats-Gatherer-Java/blob/d594080f12fe5c75f2801e352a2f02c371c78881/src/main/java/com/ffxivcensus/gatherer/player/PlayerBuilder.java#L204) if no minions are present.

Producing a patch now that will yield an empty array in the instance that these scenarios.

**Comment by ReidWeb** [comment] 2022-01-09 21:24
On the dev env, Jonathan and I executed a run between the ids specified above: `33,000,000` and `33,005,000`.

# Checks performed

## Check 1 - Check deleted chars against alternate gatherer

This run yielded the below results when the following query was executed

```sql
USE ffxivcensus_dev;
SELECT id FROM tblplayers
WHERE id > 33000000 AND id < 34000000 and character_status = 'DELETED';
```

[ffxivcensus_dev_tblplayers_bugfix_sample.csv](https://github.com/XIVStats/XIVStats-Gatherer-Java/files/7835907/ffxivcensus_dev_tblplayers_bugfix_sample.csv)

Sanity checking this with my script that doesn't do a minion/mount fetch, the below results are produced:

![image](https://user-images.githubusercontent.com/3649078/148700802-88135761-826a-42ff-b99a-cd7bef903d55.png)

I.e. there were no ids supplied for which my script could find a character, all characters requested were found to not exist.

✅  EXPECTED RESULT 

## Check 2 - Check known issue player - no mounts, no minions

Executing the following SQL query to check the [aforementioned character](https://eu.finalfantasyxiv.com/lodestone/character/33000006)

Yields the below result

| id | name | character\_status |
| :--- | :--- | :--- |
| 33000006 | Zana'ir Epocan | ACTIVE |

✅  EXPECTED RESULT 

## Check 3 - Check known issue player  - no mounts, has minions

```sql
USE ffxivcensus_dev;
SELECT id, name, character_status FROM tblplayers WHERE id = 33000046;
```

Yields
| id | name | character\_status |
| :--- | :--- | :--- |
| 33000046 | K'ewl D'eeps | ACTIVE |

✅  EXPECTED RESULT 

## Check 4.1 - Check count of characters with mounts, but has no minions

```sql
SELECT COUNT(id)
FROM tblplayers
WHERE mounts IS NOT NULL AND minions IS NULL AND character_status != 'DELETED' AND id > 33000000 and id < 33005000;
```

Yields

| COUNT\(id\) |
| :--- |
| 42 |

## Check 4.2 - Check count of characters with no mounts, but minions

```sql
SELECT COUNT(id)
FROM tblplayers
WHERE mounts IS NULL AND minions IS NOT NULL AND character_status != 'DELETED' AND id > 33000000 and id < 33005000;
```

Yields

| COUNT\(id\) |
| :--- |
| 150 |

## Check 4.3 - Check count of characters with no minions or mounts

```sql
SELECT COUNT(id)
FROM tblplayers
WHERE mounts IS NULL AND minions IS NULL AND character_status != 'DELETED' AND id > 33000000 and id < 33005000;
```

Yields

| COUNT\(id\) |
| :--- |
| 1596 |

## 4: Cumulative result

Based on the above query results, we can ascertain that there should be 42+150+1596=1,788 characters that would have been marked as `DELETED` with the current live version of the available 4999.

Executing the below query against PROD

```sql
SELECT COUNT(id)
FROM tblplayers
WHERE id > 33000000 and id < 33005000 AND character_status = 'DELETED';
```

Yields the below result

| COUNT\(id\) |
| :--- |
| 3946 |

If we take 1,788 (the number of characters where a mount or minion fetch error would have been thrown) from 3,946 (the number of deleted characters as recorded in prod) we get 2,158.

Executing the below in DEV

```sql
SELECT COUNT(id)
FROM tblplayers
WHERE id > 33000000 and id < 33005000 AND character_status = 'DELETED';
```

Yields the result:

| COUNT\(id\) |
| :--- |
| 2159 |

⚠️  i.e. we are one off. It's possible a character in range has been deleted since the time the prod gatherer parsed that range. For complete proof, i'll pull in the live version of the gatherer into DEV and verify it produces `2158`

 ✅  EXPECTED RESULT 

# Summary

I can state with a very high degree of confidence given the math above, that the only bug expressing itself that was yielding incorrect results was that articulated above. This bug has been proven as fixed by the change proposed in #65. 

Manual sampling 30 of the characters marked as deleted yields no result where a page does not 404.

**Closed as completed** 2022-01-09 21:34 UTC
Labels: bug

**Comment by ReidWeb** [comment] 2022-01-09 21:47
Jonathan is recommencing a census with the updated JAR, against a fresh database due to us not knowing which of the DELETED chars are bug impacted, and which are not.

Padraig is going to look at adjusting the copy on the php script in the intervening period to be ready to have an explanation for the sudden jump.

**Comment by Graphicscore** [comment] 2022-01-10 08:55
Hello everybody, in the last couple of months I was playing around with the repository in a fork. I fixed a couple of things which lead to characters being incorrectly labeled as DELETED.  I also stumbled upon this issue. There is also on an issue where the Player Image last-modified might not be correctly parsed if the system time format is not english specifically.

https://github.com/Graphicscore/XIVStats-Gatherer-Java/commit/c3f1255db1a81205c11302b5d372e874362b361c#diff-d643bf0c805f33cd0fc494be6cc92b4126f88e0245cb1c668f40a0241d0ef8d4

https://github.com/Graphicscore/XIVStats-Gatherer-Java/commit/e14622e20c0cc6934efebe1dd5bdd4d22c9969ae#diff-d643bf0c805f33cd0fc494be6cc92b4126f88e0245cb1c668f40a0241d0ef8d4

**Comment by ReidWeb** [comment] 2022-01-10 08:58
We don't run our censuses against anything other than the English lodestone so not particularly an issue. 

Nor is the image actively used to indicate activity.

**Comment by Graphicscore** [comment] 2022-01-10 09:19
I don't mean the english lodestone. For me the parsing of the date failed even though it was running in docker on an english system. If the parsing of the string fails it will thrown an exception which ultimately will mark the character as deleted as it's not being catched anywhere else.

**Comment by ReidWeb** [comment] 2022-01-10 09:31
Ah, interesting 🤔

**Comment by ReidWeb** [comment] 2022-01-10 09:35
@Graphicscore are you seeing that on particular character ids or all ids?

**Comment by matthewhillier** [comment] 2022-01-10 09:35
Nicely done @ReidWeb! My head was going in completely the wrong direction over the weekend 🙄

**Comment by Graphicscore** [comment] 2022-01-10 09:38
@ReidWeb It was for certain character ids, definitely not for all. I would have to run the cencus again without the fix to get the IDs. Can't remember which characters were affected.

**Comment by ReidWeb** [comment] 2022-01-10 09:46
Okay, would love to get those IDs if we know them.

In relation to the checks I did above in check 1, my script only fetches the base page - in the two ranges checked there was no character marked as deleted where a fetch of their base page did not fail. So no noted instances of this described scenario being encountered. Still worth investigating though.

To save confusion for anyone reading this thread, do you mind if we break the locale issue into a separate thread?
